# # Channel (or any chat id, really) to post **ALL** updates (leave comment to turn this feature off)
# channel =

# # Channel (or any chat id, really) to send errors too (leave comment to turn this feature off).
# # You can set your user id here to get notified about problems with the bot
# error_report_channel_id =

# # Delay between index fetches
# pull_delay = { secs = 300, nanos = 0 } # 5 min

# # Logging level (one of "error", "warn", "info", "debug" and "trace")
# loglevel = "info"

# # Url of crates.io index (git repo)
# index_url = "https://github.com/rust-lang/crates.io-index.git"

# # The path to the local crates.io index git repository
# index_path = "./index"

# # Delay after which bot will retry telegram-request
# retry_delay = { secs = 10, nanos = 0 }

# # Delay between broadcast send messages
# broadcast_delay_millis = 250

# # Delay between notifying about updates
# update_delay_millis = 1300

# Token of the telegram bot
bot_token = "0000000000:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

# Database configuration
[db]
host = "host"
user = "user"
dbname = "dbname"

# [ban]
# # List of names of banned crates (they won't show up in the channel)
# crates = []
